### ISSUE TITLE
Entry point for console script does not exist

### ISSUE THREAD

**Issue by penguinpee** [BlueBrain/AstroVascPy#36]
I'm looking into packaging this for Fedora. There's one last hurdle:

https://github.com/BlueBrain/AstroVascPy/blob/96107371e0d9e725fd7541b945787470bc52832a/setup.py#L74

The specified entry point does not exist. I doesn't look like there is a viable entry point at all. In any case there is no `cli` sub module provided by the package.

**Comment by tristan0x** [comment]
Thank you very much @penguinpee for both your packaging efforts and noticing the issue.
